# TCL File Generated by Component Editor 10.0sp1
# Tue Apr 15 13:34:27 BRT 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | Buffer_8bit_1024K "Buffer_8bit_1024K" v1.0
# | Franz Wagner 2014.04.15.13:34:27
# | 
# | 
# | C:/Users/franz.couto/Desktop/Prototipo_Medipix/Projeto/teste_mem/Modules/mem/Buffer_8bit_1024K.v
# | 
# |    ./Buffer_8bit_1024K.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module Buffer_8bit_1024K
# | 
set_module_property NAME Buffer_8bit_1024K
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Memories and Memory Controllers/SRAM"
set_module_property AUTHOR "Franz Wagner"
set_module_property DISPLAY_NAME Buffer_8bit_1024K
set_module_property TOP_LEVEL_HDL_FILE Buffer_8bit_1024K.v
set_module_property TOP_LEVEL_HDL_MODULE Buffer_8bit_1024K
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file Buffer_8bit_1024K.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 10
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice true
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_sink
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave oDATA readdata Output 8
add_interface_port avalon_slave iDATA writedata Input 8
add_interface_port avalon_slave iADDR address Input 10
add_interface_port avalon_slave iWE_N write Input 1
add_interface_port avalon_slave iOE_N read Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end Buffer_DQ export Bidir 8
add_interface_port conduit_end Buffer_ADDR export Output 10
add_interface_port conduit_end Buffer_WE_N export Output 1
add_interface_port conduit_end Buffer_OE_N export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink iCLK clk Input 1
# | 
# +-----------------------------------
