# TCL File Generated by Component Editor 8.0
# Fri Jul 18 16:46:12 CEST 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | i2c_master "i2c_master" v1.0.1
# | null 2008.07.18.16:46:12
# | 
# | 
# | /home/erik/Desktop/cycloneIII_embedded_evaluation_kit_standard_ocm/ip/i2c_master/hdl/i2c_master.v
# | 
# |    ./hdl/i2c_master_bit_ctrl.v syn, sim
# |    ./hdl/i2c_master_byte_ctrl.v syn, sim
# |    ./hdl/i2c_master_defines.v syn, sim
# |    ./hdl/i2c_master_top.v syn, sim
# |    ./hdl/i2c_master.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module i2c_master
# | 
set_module_property NAME i2c_master
set_module_property VERSION 1.0.1
set_module_property GROUP Franz/Communication
set_module_property DISPLAY_NAME i2c_master
set_module_property TOP_LEVEL_HDL_FILE hdl/i2c_master.v
set_module_property TOP_LEVEL_HDL_MODULE i2c_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/i2c_master_bit_ctrl.v {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_byte_ctrl.v {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_defines.v {SYNTHESIS SIMULATION}
add_file hdl/i2c_master_top.v {SYNTHESIS SIMULATION}
add_file hdl/i2c_master.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ptfSchematicName ""

add_interface_port clk clk clk Input 1
add_interface_port clk reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_export
# | 
add_interface avalon_slave_export conduit end

set_interface_property avalon_slave_export ASSOCIATED_CLOCK clk

add_interface_port avalon_slave_export i2c_scl export Bidir 1
add_interface_port avalon_slave_export i2c_sda export Bidir 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave minimumUninterruptedRunLength 1
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave addressSpan 8
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave printableDevice false

set_interface_property avalon_slave ASSOCIATED_CLOCK clk

add_interface_port avalon_slave address address Input 3
add_interface_port avalon_slave writedata writedata Input 8
add_interface_port avalon_slave readdata readdata Output 8
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_irq
# | 
add_interface avalon_slave_irq interrupt end
set_interface_property avalon_slave_irq associatedAddressablePoint avalon_slave

set_interface_property avalon_slave_irq ASSOCIATED_CLOCK clk

add_interface_port avalon_slave_irq irq irq Output 1
# | 
# +-----------------------------------
