# TCL File Generated by Component Editor 8.1
# Mon Oct 26 11:49:01 GMT-03:00 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | txtable "txtable" v1.0
# | null 2009.10.26.11:49:01
# | 
# | 
# | D:/Juliano/Projetos/Mux/projeto/173_MultiplexIFX_newCPU_ISMUX002_SFN/Multiplexer_ISDB/txtable/txtable.vhd
# | 
# |    ./txtable.vhd syn, sim
# |    ./avalon_wrdata.vhd syn, sim
# |    ./txdata_tovhdl.vhd syn, sim
# |    ./IP_ram_txtable.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module txtable
# | 
set_module_property NAME txtable
set_module_property VERSION 1.0
set_module_property GROUP Franz/Ts_table
set_module_property DISPLAY_NAME txtable
set_module_property LIBRARIES {ieee.std_logic_1164.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE txtable.vhd
set_module_property TOP_LEVEL_HDL_MODULE txtable
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file txtable.vhd {SYNTHESIS SIMULATION}
add_file avalon_wrdata.vhd {SYNTHESIS SIMULATION}
add_file txdata_tovhdl.vhd {SYNTHESIS SIMULATION}
add_file IP_ram_txtable.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset rst_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressSpan 16
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 minimumUninterruptedRunLength 1
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset

add_interface_port conduit_end out_sync export Output 1
add_interface_port conduit_end out_valid export Output 1
add_interface_port conduit_end out_data export Output 8
add_interface_port conduit_end in_Nreset export Input 1
add_interface_port conduit_end clock_vhdl export Input 1
add_interface_port conduit_end irq export Output 1
add_interface_port conduit_end info_out export Output 8
# | 
# +-----------------------------------
